"""empty message

Revision ID: 0c7363f25b7e
Revises: c892eb9da2e0
Create Date: 2017-07-27 19:10:14.224027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c7363f25b7e'
down_revision = 'c892eb9da2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('left_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_leaving', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('designation', sa.String(length=45), nullable=False),
    sa.Column('department', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('status', mysql.ENUM('Current', 'Left'), nullable=False))
    op.drop_table('left_employees')
    # ### end Alembic commands ###
