"""empty message

Revision ID: 1efa1d673d24
Revises: c70cb80cf582
Create Date: 2018-02-24 19:43:32.506106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1efa1d673d24'
down_revision = 'c70cb80cf582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'reporting_manager_name')
    op.drop_column('employees', 'reporting_manager_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('reporting_manager_email', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('reporting_manager_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
