"""empty message

Revision ID: 37869fd30c0b
Revises: d7416918b930
Create Date: 2017-07-27 19:24:45.792906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37869fd30c0b'
down_revision = 'd7416918b930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'total_medical_leaves')
    op.drop_column('employees', 'total_general_leaves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('total_general_leaves', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('total_medical_leaves', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
