"""empty message

Revision ID: 3f0de2cefa62
Revises: 1efa1d673d24
Create Date: 2018-02-24 19:44:01.774762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0de2cefa62'
down_revision = '1efa1d673d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('reporting_manager_email', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('reporting_manager_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'reporting_manager_name')
    op.drop_column('employees', 'reporting_manager_email')
    # ### end Alembic commands ###
