"""empty message

Revision ID: 601215be4308
Revises: d619afe04eb8
Create Date: 2017-07-23 20:41:01.066219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601215be4308'
down_revision = 'd619afe04eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.Enum('Admin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
