"""empty message

Revision ID: a4902c7c9e4b
Revises: 
Create Date: 2017-07-18 23:56:53.536079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4902c7c9e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('user', 'names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('names', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
