"""empty message

Revision ID: c7951fba0598
Revises: 
Create Date: 2018-02-24 19:01:44.460315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7951fba0598'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=45), nullable=False),
    sa.Column('value', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('balance_sheet', 'manager_approval',
               existing_type=mysql.ENUM('Approved', 'Unapproved'),
               nullable=True)
    op.drop_column('balance_sheet', 'hr_approval')
    op.add_column('employees', sa.Column('date_of_joining', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('general_leaves_availed', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('general_leaves_remaining', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('medical_leaves_availed', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('medical_leaves_remaining', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('reporting_manager_email', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('reporting_manager_name', sa.Integer(), nullable=True))
    op.drop_column('employees', 'reporting_manager')
    op.drop_column('employees', 'total_leaves_allowed')
    op.drop_column('employees', 'leaves_availed')
    op.drop_column('employees', 'leaves_remaining')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('leaves_remaining', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('leaves_availed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('total_leaves_allowed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('reporting_manager', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('employees', 'reporting_manager_name')
    op.drop_column('employees', 'reporting_manager_email')
    op.drop_column('employees', 'medical_leaves_remaining')
    op.drop_column('employees', 'medical_leaves_availed')
    op.drop_column('employees', 'general_leaves_remaining')
    op.drop_column('employees', 'general_leaves_availed')
    op.drop_column('employees', 'date_of_joining')
    op.add_column('balance_sheet', sa.Column('hr_approval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('balance_sheet', 'manager_approval',
               existing_type=mysql.ENUM('Approved', 'Unapproved'),
               nullable=False)
    op.drop_table('settings')
    # ### end Alembic commands ###
