"""empty message

Revision ID: c892eb9da2e0
Revises: 601215be4308
Create Date: 2017-07-27 18:41:11.257508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c892eb9da2e0'
down_revision = '601215be4308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_sheet', 'hr_approval')
    op.add_column('employees', sa.Column('date_of_joining', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('general_leaves_availed', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('general_leaves_remaining', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('medical_leaves_availed', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('medical_leaves_remaining', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('status', sa.Enum('Current', 'Left'), nullable=False))
    op.add_column('employees', sa.Column('total_general_leaves', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('total_medical_leaves', sa.Integer(), nullable=False))
    op.drop_column('employees', 'total_leaves_allowed')
    op.drop_column('employees', 'leaves_remaining')
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'leaves_availed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('leaves_availed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role', mysql.ENUM('Admin'), nullable=True))
    op.add_column('employees', sa.Column('leaves_remaining', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('total_leaves_allowed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('employees', 'total_medical_leaves')
    op.drop_column('employees', 'total_general_leaves')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'medical_leaves_remaining')
    op.drop_column('employees', 'medical_leaves_availed')
    op.drop_column('employees', 'general_leaves_remaining')
    op.drop_column('employees', 'general_leaves_availed')
    op.drop_column('employees', 'date_of_joining')
    op.add_column('balance_sheet', sa.Column('hr_approval', mysql.ENUM('Approved', 'Unapproved'), nullable=True))
    # ### end Alembic commands ###
