"""empty message

Revision ID: d619afe04eb8
Revises: 4c0f9e3adc37
Create Date: 2017-07-23 17:07:58.249994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd619afe04eb8'
down_revision = '4c0f9e3adc37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
